app_cuentas/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views
from . import views

app_name = 'cuentas'

urlpatterns = [
    path('registro/', views.registro, name='registro'),    
    path('login/', LoginView.as_view(template_name="app_cuentas/login.html"), name='login'),    
    path('logout/', LogoutView.as_view(template_name="app_cuentas/logout.html"), name='logout'),    
    path('perfil/', views.perfil_ver, name='perfil_ver'),
    path('perfil/editar/', views.perfil_editar, name='perfil_editar'),    
    path('perfil/cambiar-password/', views.cambiar_password, name='cambiar_password'),    
    path('perfil/<str:cod_user>/', views.perfil_publico, name='perfil_publico'),

]

app_ecommerce/urls.py
from django.urls import path
from . import views

app_name = 'app_ecommerce'

urlpatterns = [
    path('', views.index, name='index'),
    path('clientes/registrar/', views.cliente, name='cliente'),        
    path('productos/', views.ProductoListView.as_view(), name='producto_listar'),
    path('productos/nuevo/', views.ProductoCreateView.as_view(), name='producto_crear'),    
    path('productos/<str:cod_prod>/', views.ProductoDetailView.as_view(), name='producto_detalle'),
    path('productos/<str:cod_prod>/editar/', views.ProductoUpdateView.as_view(), name='producto_editar'),
    path('productos/<str:cod_prod>/borrar/', views.ProductoDeleteView.as_view(), name='producto_eliminar'),    
    path('buscar/', views.buscar, name='buscar'),    
    path('productos/<str:cod_prod>/like/', views.producto_like, name='producto_like'),


]

app_operaciones/urls.py
from django.urls import path
from . import views

app_name = 'app_operaciones'

urlpatterns = [
    path('tipodoc/', views.tipodoc_list, name='tipodoc_listar'),
    path('tipodoc/crear/', views.tipodoc, name='tipodoc_crear'),
    path('tipodoc/editar/<int:pk>/', views.tipodoc_editar, name='tipodoc_editar'),
    path('tipodoc/eliminar/<int:pk>/', views.tipodoc_eliminar, name='tipodoc_eliminar'),

    path('categoria/', views.categoria_list, name='categoria_listar'),
    path('categoria/crear/', views.categoria, name='categoria_crear'),
    path('categoria/editar/<int:pk>/', views.categoria_editar, name='categoria_editar'),
    path('categoria/eliminar/<int:pk>/', views.categoria_eliminar, name='categoria_eliminar'),


    path('pedido/', views.pedido_list, name='pedido_listar'),
    path('pedido/crear/', views.pedido, name='pedido_crear'),
    path('pedido/editar/<int:pk>/', views.pedido_editar, name='pedido_editar'),
    path('pedido/eliminar/<int:pk>/', views.pedido_eliminar, name='pedido_eliminar'),
]

tp_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_ecommerce.urls')),
    path('cuentas/', include('app_cuentas.urls')),
    path('paginas/', include('app_paginas.urls')),
    path('operaciones/', include('app_operaciones.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_operaciones/models.py
from django.db import models
import uuid

def generar_code():
    return uuid.uuid4().hex

class TipoDoc(models.Model):
    nombre = models.CharField(max_length=7, unique=True)
    descripcion = models.TextField(blank=True)

    def __str__(self):
        return self.nombre



class Categoria(models.Model):
    nombre = models.CharField(max_length=50, unique=True)
    descripcion = models.TextField(blank=True)

    def __str__(self):
        return self.nombre

class Pedido(models.Model):
    cod_ped = models.CharField(max_length=32, unique=True, default=generar_code)
    cliente = models.ForeignKey('app_cuentas.Perfil', on_delete=models.CASCADE)
    producto = models.ManyToManyField('app_ecommerce.Producto', through='DetallePedido')
    cantidad = models.PositiveIntegerField(default=1)
    fecha_pedido = models.DateTimeField(auto_now_add=True)
    total = models.DecimalField(max_digits=21, decimal_places=2, default=0)

    def calcular_total(self):
        return sum(det.subtotal for det in self.detallepedido_set.all())
    
    def save(self, *args, **kwargs):
        # calcular total automáticamente si hay producto y cantidad
        try:
            self.total = self.calcular_total()
        except Exception:
            self.total = 0
        super().save(*args, **kwargs)
        
    def __str__(self):
        return f"Pedido #{self.cod_ped} - {self.cliente}"

    
class DetallePedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    producto = models.ForeignKey('app_ecommerce.Producto', on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)
    subtotal = models.DecimalField(max_digits=21, decimal_places=2)

    def __str__(self):
        return f"{self.producto} x {self.cantidad}"


app_operaciones/forms.py
from django import forms
from .models import Categoria, TipoDoc, Pedido, DetallePedido
from app_ecommerce.models import Producto
from app_cuentas.models import Perfil

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nombre', 'descripcion']
        widgets = {
            "nombre" : forms.TextInput(attrs={'class': 'form-control'}),
            "descripcion" : forms.TextInput(attrs={'class': 'form-control'}),
        }

class TipoDocForm(forms.ModelForm):
    class Meta:
        model = TipoDoc
        fields = ['nombre', 'descripcion']
        widgets = {
            "nombre" : forms.TextInput(attrs={'class': 'form-control'}),
            "descripcion" : forms.TextInput(attrs={'class': 'form-control'}),
        }

class PedidoForm(forms.ModelForm):
    producto = forms.ModelMultipleChoiceField(
        queryset=Producto.objects.all(),
        widget=forms.SelectMultiple(attrs={'class': 'form-control'})
    )
    class Meta:
        model = Pedido
        fields = ['cliente', 'producto', 'cantidad']
        widgets = {
            'cliente': forms.Select(attrs={'class': 'form-control'}),            
            'cantidad': forms.NumberInput(attrs={'class': 'form-control', 'min': 1}),
        }

app_operaciones/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages
from .models import TipoDoc, Categoria, Pedido, DetallePedido
from .forms import CategoriaForm, TipoDocForm, PedidoForm
from django.contrib.auth.decorators import login_required
from decimal import Decimal, ROUND_HALF_UP


# *** Categoria ***
@login_required
def categoria_list(request):
    categorias = Categoria.objects.all()
    return render(request, 'app_operaciones/categoria_list.html', {'categorias': categorias})

@login_required
def categoria(request):
    if request.method == "POST":
        form = CategoriaForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Categoría registrada.")            
            return redirect('app_operaciones:categoria_listar')
    else:
        form = CategoriaForm()    
    return render(request, 'app_operaciones/categoria_form.html', {'form': form})

@login_required
def categoria_editar(request, pk):
    cat = get_object_or_404(Categoria, pk=pk)
    if request.method == "POST":
        form = CategoriaForm(request.POST, instance=cat)
        if form.is_valid():
            form.save()
            messages.success(request, "Categoría actualizada.")
            return redirect('app_operaciones:categoria_listar')
    else:
        form = CategoriaForm(instance=cat)
    return render(request, 'app_operaciones/categoria_form.html', {'form': form})

@login_required
def categoria_eliminar(request, pk):
    cat = get_object_or_404(Categoria, pk=pk)
    cat.delete()
    messages.success(request, "Categoría eliminada.")
    return redirect('app_operaciones:categoria_listar')
# *** Categoria ***


# *** Tipo Doc ***
@login_required
def tipodoc_list(request):
    tiposdoc = TipoDoc.objects.all()
    return render(request, 'app_operaciones/tipodoc_list.html', {'tiposdoc': tiposdoc})

@login_required
def tipodoc(request):
    if request.method == "POST":
        form = TipoDocForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Tipo de documento registrado.")
            #return redirect('app_ecommerce:index')
            return redirect('app_operaciones:tipodoc_listar')
    else:
        form = TipoDocForm()    
    return render(request, 'app_operaciones/tipodoc_form.html', {'form': form})

@login_required
def tipodoc_editar(request, pk):
    td = get_object_or_404(TipoDoc, pk=pk)
    if request.method == "POST":
        form = TipoDocForm(request.POST, instance=td)
        if form.is_valid():
            form.save()
            messages.success(request, "Tipo de documento actualizado.")
            return redirect('app_operaciones:tipodoc_listar')
    else:
        form = TipoDocForm(instance=td)
    return render(request, 'app_operaciones/tipodoc_form.html', {'form': form})

@login_required
def tipodoc_eliminar(request, pk):
    td = get_object_or_404(TipoDoc, pk=pk)
    td.delete()
    messages.success(request, "Tipo de documento eliminado.")
    return redirect('app_operaciones:tipodoc_listar')
# *** Tipo Doc ***

# *** Pedido ***
@login_required
def pedido_list(request):
    pedidos = Pedido.objects.all().order_by('-fecha_pedido')
    return render(request, 'app_operaciones/pedido_list.html', {'pedidos': pedidos})

@login_required
def pedido(request):
    if request.method == "POST":
        form = PedidoForm(request.POST)
        if form.is_valid():
            pedido = form.save(commit=False)
            # inicializamos total
            pedido.total = Decimal('0.00')
            pedido.save()  # primero guardamos el pedido para tener ID

            productos = form.cleaned_data['producto']  # QuerySet de productos            
            cantidades = request.POST.getlist('cantidad')  # si hay input separado por cantidad

            for i, producto in enumerate(productos):
                cantidad = int(cantidades[i]) if i < len(cantidades) else 1
                print(f"cantidades: {request.POST.getlist('cantidad')}")
                print(f"cantidades: {cantidades}")
                print(f"cantidades: {cantidad}")                
                precio = Decimal(str(producto.precio))                
                subtotal = (precio * Decimal(cantidad)).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
                pedido.total += subtotal

                # guardamos en DetallePedido
                from .models import DetallePedido
                DetallePedido.objects.create(
                    pedido=pedido,
                    producto=producto,
                    cantidad=cantidad,
                    subtotal=subtotal
                )

            pedido.total = pedido.total.quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)

            pedido.save()  # actualizamos total
            messages.success(request, f"Pedido #{pedido.id} registrado correctamente.")
            return redirect('app_operaciones:pedido_crear')
    else:
        form = PedidoForm()

    return render(request, 'app_operaciones/pedido_form.html', {'form': form})

# Si no se desea editar un pedido. En pedido_list.html, comentar el boton de edicion
#@login_required
#def pedido_editar(request, pk):
#    pedido_obj = get_object_or_404(Pedido, pk=pk)
#
#    if request.method == "POST":
#        form = PedidoForm(request.POST, instance=pedido_obj)
#        if form.is_valid():
#            pedido = form.save(commit=False)
#            # recalcular total
#            total = 0
#            for detalle in pedido.detallepedido_set.all():
#                total += detalle.subtotal
#            pedido.total = total
#            pedido.save()
#            messages.success(request, f"Pedido #{pedido.cod_ped} actualizado.")
#            return redirect('app_operaciones:pedido_listar')
#    else:
#        form = PedidoForm(instance=pedido_obj)
#    return render(request, 'app_operaciones/pedido_form.html', {'form': form})


# Si se desea editar un pedido
@login_required
def pedido_editar(request, pk):
    pedido_obj = get_object_or_404(Pedido, pk=pk)

    if request.method == "POST":
        form = PedidoForm(request.POST, instance=pedido_obj)
        if form.is_valid():
            pedido = form.save(commit=False)
            pedido.total = Decimal('0.00')
            pedido.save()

            # Eliminamos los detalles anteriores
            pedido.detallepedido_set.all().delete()

            productos = form.cleaned_data['producto']
            cantidades = request.POST.getlist('cantidad')

            for i, producto in enumerate(productos):
                cantidad = int(cantidades[i]) if i < len(cantidades) else 1
                precio = Decimal(str(producto.precio))
                subtotal = (precio * Decimal(cantidad)).quantize(Decimal('0.01'))

                # Creamos nuevamente los detalles
                DetallePedido.objects.create(
                    pedido=pedido,
                    producto=producto,
                    cantidad=cantidad,
                    subtotal=subtotal
                )
                pedido.total += subtotal

            pedido.total = pedido.total.quantize(Decimal('0.01'))
            pedido.save()

            messages.success(request, f"Pedido #{pedido.cod_ped} actualizado correctamente.")
            return redirect('app_operaciones:pedido_listar')
    else:
        form = PedidoForm(instance=pedido_obj)

    return render(request, 'app_operaciones/pedido_form.html', {'form': form})






@login_required
def pedido_eliminar(request, pk):
    pedido_obj = get_object_or_404(Pedido, pk=pk)
    pedido_obj.delete()
    messages.success(request, f"Pedido #{pedido_obj.cod_ped} eliminado.")
    return redirect('app_operaciones:pedido_listar')
# *** Pedido ***




app_operaciones/templates/app_operaciones/categoria_form.html
{% extends 'app_ecommerce/base.html' %}
{% load static %}

{% block title %}Registrar Categoría{% endblock %}

{% block content %}
<div class="card shadow-sm p-4 mx-auto" style="max-width: 600px;">
  <h3 class="text-center mb-4">Registrar Categoría</h3>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="text-center mt-3">
      <button type="submit" class="btn btn-success px-4">Guardar</button>
      <a href="{% url 'app_ecommerce:index' %}" class="btn btn-secondary">Cancelar</a>
    </div>
    <div class="text-center mt-3">
        <a href="{% url 'app_operaciones:categoria_listar' %}" class="btn btn-secondary">Ver Categorias</a>
    </div>
  </form>
</div>
{% endblock %}



app_operaciones/templates/app_operaciones/categoria_list.html
{% extends 'app_ecommerce/base.html' %}
{% block title %}Categorías{% endblock %}

{% block content %}
<div class="container mt-4">
  <h2>Categorías</h2>
  <a href="{% url 'app_operaciones:categoria_crear' %}" class="btn btn-primary mb-2">Nueva Categoría</a>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Descripción</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% for cat in categorias %}
      <tr>
        <td>{{ cat.nombre }}</td>
        <td>{{ cat.descripcion }}</td>
        <td>
          <a href="{% url 'app_operaciones:categoria_editar' cat.id %}" class="btn btn-sm btn-warning">Editar</a>
          <a href="{% url 'app_operaciones:categoria_eliminar' cat.id %}" class="btn btn-sm btn-danger">Eliminar</a>
        </td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="3">No hay categorías.</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app_operaciones/templates/app_operaciones/pedido_form.html
{% extends 'app_ecommerce/base.html' %}
{% load static %}

{% block title %}Pedidos{% endblock %}

{% block content %}
<div class="card shadow-sm p-4 mx-auto" style="max-width: 600px;">
  <h3 class="text-center mb-4">Gestión de Pedidos</h3>

  {% if messages %}
    <div>
      {% for message in messages %}
        <div class="alert alert-success">{{ message }}</div>
      {% endfor %}
    </div>
  {% endif %}

  <form method="post">
    {% csrf_token %}

    {{ form.as_p }}
    <div class="text-center mt-3">
        <button type="submit" class="btn btn-success w-100">Registrar Pedido</button>
        <a href="{% url 'app_ecommerce:index' %}" class="btn btn-secondary">Cancelar</a>
    </div>
    <div class="text-center mt-3">
        <a href="{% url 'app_operaciones:pedido_listar' %}" class="btn btn-secondary">Ver Pedidos</a>
    </div>
  </form>
</div>
{% endblock %}



app_operaciones/templates/app_operaciones/pedido_list.html
{% extends 'app_ecommerce/base.html' %}
{% block title %}Pedidos{% endblock %}

{% block content %}
<div class="container mt-4">
  <h2>Pedidos</h2>
  <a href="{% url 'app_operaciones:pedido_crear' %}" class="btn btn-primary mb-2">Nuevo Pedido</a>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nro Pedido</th>
        <th>Cliente</th>
        <th>Fecha Pedido</th>
        <th>Productos</th>
        <th>Total</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% for ped in pedidos %}
      <tr>
        <td>{{ ped.cod_ped }}</td>
        <td>{{ ped.cliente }}</td>
        <td>{{ ped.fecha_pedido|date:"d-m-Y H:i" }}</td>
        <td>
          <ul>
            {% for det in ped.detallepedido_set.all %}
            <li>{{ det.producto.nombre }} x {{ det.cantidad }}: ${{ det.subtotal }}</li>
            {% endfor %}
          </ul>
        </td>
        <td>${{ ped.total }}</td>
        <td>
          <a href="{% url 'app_operaciones:pedido_editar' ped.id %}" class="btn btn-sm btn-warning">Editar</a>
          <a href="{% url 'app_operaciones:pedido_eliminar' ped.id %}" class="btn btn-sm btn-danger">Eliminar</a>
        </td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="6">No hay pedidos registrados.</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app_operaciones/templates/app_operaciones/tipodoc_form.html
{% extends 'app_ecommerce/base.html' %}
{% load static %}

{% block title %}Registrar Documento{% endblock %}

{% block content %}
<div class="card shadow-sm p-4 mx-auto" style="max-width: 600px;">
  <h3 class="text-center mb-4">Registrar Documento</h3>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="text-center mt-3">
      <button type="submit" class="btn btn-success px-4">Guardar</button>
      <a href="{% url 'app_ecommerce:index' %}" class="btn btn-secondary">Cancelar</a>
    </div>
    <div class="text-center mt-3">
        <a href="{% url 'app_operaciones:tipodoc_listar' %}" class="btn btn-secondary">Ver Documentos</a>
    </div>
  </form>
</div>
{% endblock %}

app_operaciones/templates/app_operaciones/tipodoc_list.html
{% extends 'app_ecommerce/base.html' %}
{% block title %}Tipos de Documento{% endblock %}

{% block content %}
<div class="container mt-4">
  <h2>Tipos de Documento</h2>
  <a href="{% url 'app_operaciones:tipodoc_crear' %}" class="btn btn-primary mb-2">Nuevo TipoDoc</a>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Descripción</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% for td in tiposdoc %}
      <tr>
        <td>{{ td.nombre }}</td>
        <td>{{ td.descripcion }}</td>
        <td>
          <a href="{% url 'app_operaciones:tipodoc_editar' td.id %}" class="btn btn-sm btn-warning">Editar</a>
          <a href="{% url 'app_operaciones:tipodoc_eliminar' td.id %}" class="btn btn-sm btn-danger">Eliminar</a>
        </td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="3">No hay tipos de documento.</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}